AWSTemplateFormatVersion: '2010-09-09'
Description: VPC with one public and one private subnet, DNS enabled, no NAT. Tagged for project "nf-bootcamp".

Parameters:
  VpcCidr:
    Type: String
    Default: 10.200.123.0/24
    Description: VPC CIDR block

  PublicSubnetCidr:
    Type: String
    Default: 10.200.123.0/28
    Description: Public subnet CIDR block

  PrivateSubnetCidr:
    Type: String
    Default: 10.200.123.128/28
    Description: Private subnet CIDR block

  AvailabilityZone:
    Type: String
    Description: Availability Zone to deploy subnets

  ProjectTag:
    Type: String
    Default: nf-bootcamp
    Description: Project tag to apply to all resources

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: nf-bootcamp-vpc
        - Key: Project
          Value: !Ref ProjectTag

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: nf-bootcamp-igw
        - Key: Project
          Value: !Ref ProjectTag

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PublicSubnetCidr
      AvailabilityZone: !Ref AvailabilityZone
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub nf-public-subnet-${AvailabilityZone}
        - Key: Project
          Value: !Ref ProjectTag

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PrivateSubnetCidr
      AvailabilityZone: !Ref AvailabilityZone
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub nf-private-subnet-${AvailabilityZone}
        - Key: Project
          Value: !Ref ProjectTag

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub nf-public-rt-${AvailabilityZone}
        - Key: Project
          Value: !Ref ProjectTag

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachInternetGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub nf-private-rt-${AvailabilityZone}
        - Key: Project
          Value: !Ref ProjectTag

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

Outputs:
  VpcId:
    Description: The VPC ID
    Value: !Ref MyVPC
  PublicSubnetId:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet
  PrivateSubnetId:
    Description: Private Subnet ID
    Value: !Ref PrivateSubnet
